"""
    This module handles the transformations for this training spark job.
"""

# Standard Library Imports <- This is not required but useful to separate out imports
from helper_printer import print_header
from pyspark.sql import DataFrame, Window
from pyspark.sql import functions as F
import helper_spark_data_generator as sdg


def job_transform_phase(dataframe: DataFrame):
    """
    1. Mocks the input dataframe with a record change type. This is a typical step in ETL jobs. By determining the
    record change type, you can handle the data differently as the job requires.
    2. Calculates the grand total for the `amount` column. This allows us to calculate the percent of total for each
    record.
    3. Creates a new column for each field that is of string datatype and changes the value to uppercase when the
    record change type value is update.
    4. Creates a new column that calculates the percent of total for each record.

    Examples:
        process_df = handle_transaction_data.job_transform_phase(dataframe=input_df)

    Args:
        dataframe (DataFrame): The dataframe to execute the transformations

    Returns:
        DataFrame
    """
    print_header("TRANSFORM 1 of 2\n"
                 "\n"
                 "Determine Record Change Type & Calculate Grant Total For Amount\n"
                 " ╠ Added a new column named `random_change_type` that is randomly\n"
                 " ╠ generated by a UDF and is one of: new, update, delete, no_change.\n"
                 " ╠ Added a new column that uses a window function to add the\n"
                 " ╚ Grand Total for Amount.")
    change_type_df = dataframe \
        .select(F.col("*"),
                sdg.get_record_action().alias("random_change_type"),
                (F.sum(F.col("amount")).over(Window.orderBy(F.lit(1)))).alias("amount_grand_total")) \
        .where(F.col("random_change_type") != "no_change")
    change_type_df.show(truncate=False)

    print_header("TRANSFORM 2 of 2\n"
                 "\n"
                 "Process Data Based On Change Type & Calculate Percent Of Total\n"
                 " ╠ Updated (actually a new column of the same name) all column datatypes of string\n"
                 " ╠ to uppercase when the change type is `update`.\n"
                 " ╚ Added a new column that calculates the percent of total for amount")
    column_select_list = []
    for col_name, col_type in change_type_df.dtypes:
        if col_type == "string":
            column_select_list.append(
                F.when(F.col("random_change_type") == "update", F.upper(F.col(col_name)))
                .otherwise(F.col(col_name))
                .alias(col_name))
        else:
            column_select_list.append(F.col(col_name).alias(col_name))
    _process_df = change_type_df \
        .select(*column_select_list,
                F.round(F.col("amount") / F.col("amount_grand_total"), 2).alias("amount_percent_of_total")) \
        .drop(F.col("amount_grand_total"))
    _process_df.show(truncate=False)
    return _process_df
